name: Process log items
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  BUCKET_URI: ${{ secrets.BUCKET_URI }}
  BUCKET_CREDENTIALS: ${{ secrets.BUCKET_CREDENTIALS }}
  FALLBACK_BUCKET_URI: ${{ secrets.FALLBACK_BUCKET_URI }}
  FALLBACK_BUCKET_CREDENTIALS: ${{ secrets.FALLBACK_BUCKET_CREDENTIALS }}
on:
  workflow_dispatch:
jobs:
  Processing:
    runs-on: ubuntu-latest
    container:
      image: magland/kachery-gateway-processing:0.1.0
    steps:
      - name: Migrate logs
        run: cd /working && npm run migrate-logs
      - name: Migrate clients
        run: cd /working && npm run migrate-clients