name: Process log items
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  ADMIN_BUCKET_URI: ${{ secrets.ADMIN_BUCKET_URI }}
  ADMIN_BUCKET_CREDENTIALS: ${{ secrets.ADMIN_BUCKET_CREDENTIALS }}
on:
  workflow_dispatch:
jobs:
  Process-Log-Items:
    runs-on: ubuntu-latest
    container:
      image: magland/kachery-gateway-processing
    steps:
      - name: Process log items
        run: cd /working && npm run process-log-items