name: Process log items
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  BUCKET_URI: ${{ secrets.BUCKET_URI }}
  BUCKET_CREDENTIALS: ${{ secrets.BUCKET_CREDENTIALS }}
on:
  workflow_dispatch:
  schedule:
    - cron: "37 6,12,18 * * *"
jobs:
  Processing:
    runs-on: ubuntu-latest
    container:
      image: magland/kachery-gateway-processing:0.1.0
    steps:
      - name: Cleanup findFile cache
        run: cd /working && npm run cleanup-find-file-cache
      - name: Process log items
        run: cd /working && npm run process-log-items
      - name: Analyze logs
        run: cd /working && npm run analyze-logs