name: Process log items
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  ADMIN_BUCKET_URI: ${{ secrets.ADMIN_BUCKET_URI }}
  ADMIN_BUCKET_CREDENTIALS: ${{ secrets.ADMIN_BUCKET_CREDENTIALS }}
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  Processing:
    runs-on: ubuntu-latest
    container:
      image: magland/kachery-gateway-processing:0.1.0
    steps:
      - name: Process log items
        run: cd /working && npm run process-log-items
      - name: Analyze logs
        run: cd /working && npm run analyze-logs